### PR TITLE
minor: adding more badges in

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @tractorcow 

do you think you could merge this in as well?

Spek

**Comment by tractorcow** [comment]
Some of your links are broken sorry. :)

**Comment by spekulatius** [comment]
Oh, sorry. Copy and paste :/ I fixed this @tractorcow

**Comment by tractorcow** [comment]
Still broken; Packagist links should be silverstripe/multiform not silverstripe/silverstripe-multiform

**Comment by spekulatius** [comment]
(facepalm) sorry @tractorcow

**Comment by tractorcow** [comment]
Perfect!

**Pull request merged**
