### PR TITLE
Highlighting the completed steps with a CSS class

### PR DESCRIPTION
**Pull request by spekulatius**
I had a use case where we needed to highlight the completed steps in the multiform. This seems like a common use case and I feel like this might be worth to be available for everyone.

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @dhensby ,

do you think you could check this and maybe merge it in? That would be great. Thanks :)

Spek

**Comment by dhensby** [comment]
@spekulatius I'm not familiar enough to know if it's ok.

@tractorcow ?

**Comment by tractorcow** [comment]
`completed` isn't really a standard linkingmode though, is it? Should it be a separate css class field, or added via `addExtraClass`? (Not sure if  It would break any `<% if $LinkingMode = 'link' %>` condition.

**Comment by spekulatius** [comment]
Hello @tractorcow 

you are right. I didn't consider the option that someone might check for the linkingMode. I changed it back and added the functionality via extraClass. Maybe you could have a look again?

Cheers,
Spek

**Comment by tractorcow** [comment]
It looks good to me from a code point of view. :)

You will just need to fix the API so that it's compatible with 3.2 (and the tests stop failing).

I think you'll need to revert https://github.com/silverstripe/silverstripe-multiform/pull/26/files?

**Comment by spekulatius** [comment]
I fixed this @tractorcow. The one remaining failure comes from multiple packages as install candidates. It should still work.

**Comment by tractorcow** [comment]
Since this branch is for 3.2 only, you'll need to remove the following from `.travis.yml` to get it working again. :dancer: 

```yaml
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.1
```

Then everything will work.

**Comment by spekulatius** [comment]
Hello @tractorcow 

Thanks for your responses and help. I have rebased the branch and removed the PHP 5.6. for 3.1. Everything is green now, woohoo :)

Cheers,
Spek

**Comment by dhensby** [comment]
I think your first 4 commits can be squashed, please can you do that and I'll merge it today @spekulatius

**Comment by spekulatius** [comment]
Done @dhensby

**Comment by dhensby** [comment]
As we are adding this to master, I can't really make a new release at the moment unless it was some kind of v2.0 pre-release.

The releases on this module don't seem to correlate to the branches... @tractorcow any ideas?

**Comment by tractorcow** [comment]
I guess if we take that the 1.1 branch is older 1.1.x-dev, master should probably be 1.2.x-dev at least?

I'll tag master as 1.2.0

**Comment by spekulatius** [comment]
cool, thanks

**Pull request merged**
